export const ADD_PLAYLIST='ADD_PLAYLIST';
export const RANK_ADD_PLAYLIST='RANK_ADD_PLAYLIST';
export const SEARCH_ADD_PLAYLIST='SEARCH_ADD_PLAYLIST';
export const CHANGE_NOW='CHANGE_NOW';
export const REDUCE_NOW='REDUCE_NOW'